// Generated by CoffeeScript 1.3.3
"use stict";

var __slice = [].slice;

(function(root, factory) {
  var _base, _ref, _ref1;
  if ("object" === typeof exports) {
    module.exports = factory();
  } else if (typeof define !== "undefined" && define !== null ? define.amd : void 0) {
    define(factory);
  } else {
    if ((_ref = root.cosy) == null) {
      root.cosy = {};
    }
    if ((_ref1 = (_base = root.cosy).lang) == null) {
      _base.lang = {};
    }
    root.cosy.lang.dispatch = factory();
  }
})(this, function() {
  var dispatch, fn$;
  fn$ = function(def) {
    return function() {
      var args;
      args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      if (def[args.length] != null) {
        return def[args.length].apply(def, args);
      }
      if (def.$ != null) {
        return def.$.apply(def, args);
      }
      throw new Error('No default for this function');
    };
  };
  return dispatch = {
    fn$: fn$
  };
});
