// Generated by CoffeeScript 1.3.3
"use stict";

(function(root, factory) {
  var _base, _ref, _ref1;
  if ("object" === typeof exports) {
    module.exports = factory();
  } else if (typeof define !== "undefined" && define !== null ? define.amd : void 0) {
    define(factory);
  } else {
    if ((_ref = root.cosy) == null) {
      root.cosy = {};
    }
    if ((_ref1 = (_base = root.cosy).lang) == null) {
      _base.lang = {};
    }
    root.cosy.lang.identity = factory();
  }
})(this, function() {
  var identity, nextId, _id;
  identity = {};
  nextId = 0;
  _id = function(obj) {
    var id;
    if (obj.__cosy_id == null) {
      id = '$__cosy_id#' + nextId;
      nextId += 1;
      if ('function' === typeof Object.defineProperty) {
        Object.defineProperty(obj, '__cosy_id', {
          enumerable: false,
          configurable: false,
          writable: false,
          value: id
        });
      } else {
        obj.__cosy_id = id;
      }
    }
    return obj.__cosy_id;
  };
  identity.get = function(any) {
    if (any instanceof Object) {
      return _id(any);
    }
    return null;
  };
  return identity;
});
