// Generated by CoffeeScript 1.3.3
"use stict";

(function(root, factory) {
  var dispatch, identity, meta, promise, protocol, sequence, stream, tail, _base, _ref, _ref1;
  if ("object" === typeof exports) {
    dispatch = require('./dispatch');
    identity = require('./identity');
    meta = require('./meta');
    promise = require('./promise');
    protocol = require('./protocol');
    sequence = require('./sequence');
    stream = require('./stream');
    tail = require('./tail');
    module.exports = factory(dispatch, identity, meta, promise, protocol, sequence, stream, tail);
  } else if (typeof define !== "undefined" && define !== null ? define.amd : void 0) {
    define(['./dispatch', './identity', './meta', './promise', './protocol', './sequence', './stream', './tail'], factory);
  } else {
    if ((_ref = root.cosy) == null) {
      root.cosy = {};
    }
    if ((_ref1 = (_base = root.cosy).lang) == null) {
      _base.lang = {};
    }
  }
})(this, function(dispatch, identity, meta, promise, protocol, sequence, stream, tail) {
  return {
    dispatch: dispatch,
    identity: identity,
    meta: meta,
    promise: promise,
    protocol: protocol,
    sequence: sequence,
    stream: stream,
    tail: tail
  };
});
