// Generated by CoffeeScript 1.4.0

(function(root, factory) {
  var _base, _ref, _ref1;
  if ("object" === typeof exports) {
    module.exports = factory();
  } else if (typeof define !== "undefined" && define !== null ? define.amd : void 0) {
    define(factory);
  } else {
    if ((_ref = root.cosy) == null) {
      root.cosy = {};
    }
    if ((_ref1 = (_base = root.cosy).lang) == null) {
      _base.lang = {};
    }
    root.cosy.lang.meta = factory();
  }
})(this, function() {
  "use strict";

  var meta, nextId, _meta;
  meta = {};
  nextId = 0;
  _meta = function(obj) {
    if (obj.__cosy_meta == null) {
      if ('function' === typeof Object.defineProperty) {
        Object.defineProperty(obj, '__cosy_meta', {
          enumerable: false,
          configurable: false,
          writable: false,
          value: {
            _ns: {}
          }
        });
      } else {
        obj.__cosy_meta = {
          _ns: {}
        };
      }
    }
    return obj.__cosy_meta;
  };
  meta.get = function(any) {
    if (any instanceof Object) {
      return _meta(any);
    }
    return null;
  };
  meta.ns = function(any, ns) {
    var metaData, _base, _ref;
    metaData = meta.get(any);
    if (metaData != null) {
      if ((_ref = (_base = metaData._ns)[ns]) == null) {
        _base[ns] = {};
      }
      return metaData._ns[ns];
    } else {
      return null;
    }
  };
  return meta;
});
