// Generated by CoffeeScript 1.4.0
var __slice = [].slice;

(function(root, factory) {
  var _base, _ref, _ref1;
  if ("object" === typeof exports) {
    module.exports = factory();
  } else if (typeof define !== "undefined" && define !== null ? define.amd : void 0) {
    define(factory);
  } else {
    if ((_ref = root.cosy) == null) {
      root.cosy = {};
    }
    if ((_ref1 = (_base = root.cosy).lang) == null) {
      _base.lang = {};
    }
    root.cosy.lang.tail = factory();
  }
})(this, function() {
  "use strict";

  var Recur, tail;
  tail = {};
  Recur = (function() {

    function Recur(fn, args) {
      this.loop = function() {
        return fn.apply(null, args);
      };
    }

    return Recur;

  })();
  tail.recur = function() {
    var args, fn;
    fn = arguments[0], args = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
    return new Recur(fn, args);
  };
  tail.loop = function() {
    var args, fn, result;
    fn = arguments[0], args = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
    result = fn.apply(null, args);
    while (result instanceof Recur) {
      result = result.loop();
    }
    return result;
  };
  return tail;
});
