// Generated by CoffeeScript 1.4.0

(function(root, factory) {
  var protocol, _base, _ref, _ref1;
  if ("object" === typeof exports) {
    protocol = require('../protocol');
    module.exports = factory(protocol);
  } else if (typeof define !== "undefined" && define !== null ? define.amd : void 0) {
    define(['../protocol'], factory);
  } else {
    if ((_ref = root.cosy) == null) {
      root.cosy = {};
    }
    if ((_ref1 = (_base = root.cosy).lang) == null) {
      _base.lang = {};
    }
    root.cosy.lang.protocol.ISeq = factory(cost.lang.protocol);
  }
})(this, function(protocol) {
  "use strict";

  var ISeq;
  ISeq = protocol.define('ISeq', 'A logical list', ['first', 'Returns the first item in the collection. If coll is null, returns null'], ['rest', 'Returns a sequence of the items after the first. If there are no more items, returns a logical sequence for which seq returns null.']);
  return ISeq;
});
