// Generated by CoffeeScript 1.4.0

(function(root, factory) {
  var protocol, _base, _ref, _ref1;
  if ("object" === typeof exports) {
    protocol = require('../protocol');
    module.exports = factory(protocol);
  } else if (typeof define !== "undefined" && define !== null ? define.amd : void 0) {
    define(['../protocol'], factory);
  } else {
    if ((_ref = root.cosy) == null) {
      root.cosy = {};
    }
    if ((_ref1 = (_base = root.cosy).lang) == null) {
      _base.lang = {};
    }
    root.cosy.lang.protocol.IStream = factory(cost.lang.protocol);
  }
})(this, function(protocol) {
  "use strict";

  var IStream;
  IStream = protocol.define('IStream', ['tap', 'Register on emit'], ['emit', 'Emit a value']);
  IStream.skip = {
    skip: true
  };
  return IStream;
});
